### ISSUE TITLE
gcc: error: unrecognized command line option ‘-mavx2’

### ISSUE THREAD

**Issue by eonurk** [yuanyuanli85/CaffeModelCompression#4]
I got the following error while trying to build.

gcc: error: unrecognized command line option ‘-mavx2’
/usr/bin/ld: weights_compress.o: Relocations in generic ELF (EM: 62)
/usr/bin/ld: weights_compress.o: Relocations in generic ELF (EM: 62)
/usr/bin/ld: weights_compress.o: Relocations in generic ELF (EM: 62)
/usr/bin/ld: weights_compress.o: Relocations in generic ELF (EM: 62)
weights_compress.o: error adding symbols: File in wrong format

**Comment by yuanyuanli85** [comment]
AVX2 instructions are used here to accelerate the Kmeans processing. What's the version of your gcc?  Does it build if you remove "-mavx2" compiler option?

**Comment by eonurk** [comment]
I got the issue done using my other computer. However, it gave me an error;

ImportError: No module named rpn.proposal_layer
Traceback (most recent call last):
  File "caffemodel_compress.py", line 96, in <module>
    caffe_model_compress(prototxt, caffemodel, output, 6, 2)
  File "caffemodel_compress.py", line 13, in caffe_model_compress
    net = caffe.Net(model, caffe.TEST);
SystemError: NULL result without error in PyObject_Call

In the mean time, I want to ask you @yuanyuanli85 that if the compression is beneficial for making a net faster. For instance I got 500 ms detection time on Faster RCNN on Jetson TX1 module. Would the compression help to make it faster?

**Comment by kevin0932** [comment]
Hi @eonurk, I got similar questions regarding the speed-up effect of such kind of compression techniques. Did you have any progress or rough result? Personally I wonder if it can help to speed up the convolutional neural networks with only conv and no fc layers. Thanks a lot!

**Comment by eonurk** [comment]
Actually I did not have a time to strugling with this problem. But in the end, it would be very beneficial for many people to know whether compression makes it faster or not. So please let me know if you find something about the issue:)

**Comment by yuanyuanli85** [comment]
Model compression reduces the computation a lot, ie. 32-bit float ->16-bit half-float.  To run the compressed network, you need a hardware to support 16-bit half-float computation and a software framework.  As I know, Nvidia P4/P40 has the support for half-float and int8.  if we compress the weights to less bits, say 4 bits, we probably need a specific hardware, asic or fpga to run it.

**Comment by kevin0932** [comment]
@yuanyuanli85 @eonurk Thanks for replying. It is that with specific hardware and smaller data types, the reduced computation is huge. How about sticking to the 32-bit float? From what I am understanding, the saved computation mainly comes from pruning stage and the paper only benchmarks the fc layers in terms of speedup. I think the speed-up requires a really sparse weight matrix to work with cuSPARSE (as they did with fc layers and more than 95% of the parameters are pruned!) For the convolutional layers, the sparsity is only around 40%-60%. So we may only expect little speed-up or even slower computation if cuSPARSE is used? Thanks
