### ISSUE TITLE
How to implement acceleration in the paper?

### ISSUE THREAD

**Issue by larsonwu0220** [yuanyuanli85/CaffeModelCompression#5]
I am interesting in model compression and acceleration. In the paper(Deep Compression), the authors showed 3x speedup on CPU and 3.5x on GPU. But in here, I can't accelerate my AlexNet but only do compression and decompression. How to implement acceleration in the paper? Have any CNN accelerator in Caffe?
Thinks

**Comment by yuanyuanli85** [comment]
To accelerate the processing, you need to have caffe to support compressed model.  so far, that is not supported by caffe.  I am working to make the decompressed model taken by clcaffe with half-float support.
